// <auto-generated />
using EFCore3AndCSharp8.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCore3AndCSharp8.Migrations
{
    [DbContext(typeof(CatsDbContext))]
    [Migration("20200223165737_CatsDemoDb_First_added_more_rows")]
    partial class CatsDemoDb_First_added_more_rows
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCore3AndCSharp8.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("CatId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            Name = "Hamlet",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 2,
                            Name = "King Lear",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 3,
                            Name = "Othello",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 4,
                            Name = "Hamlet1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 5,
                            Name = "King Lear1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 6,
                            Name = "Hamlet",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 7,
                            Name = "King Lear",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 8,
                            Name = "Othello",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 9,
                            Name = "Hamlet1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 10,
                            Name = "King Lear1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 11,
                            Name = "Hamlet",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 12,
                            Name = "King Lear",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 13,
                            Name = "Othello",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 14,
                            Name = "Hamlet1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 15,
                            Name = "King Lear1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 16,
                            Name = "Hamlet",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 17,
                            Name = "King Lear",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 18,
                            Name = "Othello",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 19,
                            Name = "Hamlet1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 20,
                            Name = "King Lear1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 21,
                            Name = "Hamlet",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 22,
                            Name = "King Lear",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 23,
                            Name = "Othello",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 24,
                            Name = "Hamlet1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 25,
                            Name = "King Lear1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 26,
                            Name = "Hamlet",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 27,
                            Name = "King Lear",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 28,
                            Name = "Othello",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 29,
                            Name = "Hamlet1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 30,
                            Name = "King Lear1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 31,
                            Name = "Hamlet",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 32,
                            Name = "King Lear",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 33,
                            Name = "Othello",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 34,
                            Name = "Hamlet1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 35,
                            Name = "King Lear1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 36,
                            Name = "Hamlet",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 37,
                            Name = "King Lear",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 38,
                            Name = "Othello",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 39,
                            Name = "Hamlet1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 40,
                            Name = "King Lear1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 41,
                            Name = "Hamlet",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 42,
                            Name = "King Lear",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 43,
                            Name = "Othello",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 44,
                            Name = "Hamlet1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 45,
                            Name = "King Lear1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 46,
                            Name = "Hamlet",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 47,
                            Name = "King Lear",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 48,
                            Name = "Othello",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 49,
                            Name = "Hamlet1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 50,
                            Name = "King Lear1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 51,
                            Name = "Hamlet",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 52,
                            Name = "King Lear",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 53,
                            Name = "Othello",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 54,
                            Name = "Hamlet1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 55,
                            Name = "King Lear1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 56,
                            Name = "Hamlet",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 57,
                            Name = "King Lear",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 58,
                            Name = "Othello",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 59,
                            Name = "Hamlet1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 60,
                            Name = "King Lear1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 61,
                            Name = "Hamlet",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 62,
                            Name = "King Lear",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 63,
                            Name = "Othello",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 64,
                            Name = "Hamlet1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 65,
                            Name = "King Lear1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 66,
                            Name = "Hamlet",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 67,
                            Name = "King Lear",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 68,
                            Name = "Othello",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 69,
                            Name = "Hamlet1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 70,
                            Name = "King Lear1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 71,
                            Name = "Hamlet",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 72,
                            Name = "King Lear",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 73,
                            Name = "Othello",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 74,
                            Name = "Hamlet1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 75,
                            Name = "King Lear1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 76,
                            Name = "Hamlet",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 77,
                            Name = "King Lear",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 78,
                            Name = "Othello",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 79,
                            Name = "Hamlet1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 80,
                            Name = "King Lear1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 81,
                            Name = "Hamlet",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 82,
                            Name = "King Lear",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 83,
                            Name = "Othello",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 84,
                            Name = "Hamlet1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 85,
                            Name = "King Lear1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 86,
                            Name = "Hamlet",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 87,
                            Name = "King Lear",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 88,
                            Name = "Othello",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 89,
                            Name = "Hamlet1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 90,
                            Name = "King Lear1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 91,
                            Name = "Hamlet",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 92,
                            Name = "King Lear",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 93,
                            Name = "Othello",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 94,
                            Name = "Hamlet1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 95,
                            Name = "King Lear1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 96,
                            Name = "Hamlet",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 97,
                            Name = "King Lear",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 98,
                            Name = "Othello",
                            OwnerId = 1
                        },
                        new
                        {
                            CatId = 99,
                            Name = "Hamlet1",
                            OwnerId = 2
                        },
                        new
                        {
                            CatId = 100,
                            Name = "King Lear1",
                            OwnerId = 2
                        });
                });

            modelBuilder.Entity("EFCore3AndCSharp8.Models.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OwnerId");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            OwnerId = 1,
                            Name = "Hasan"
                        },
                        new
                        {
                            OwnerId = 2,
                            Name = "Faisan"
                        },
                        new
                        {
                            OwnerId = 3,
                            Name = "Parvez"
                        },
                        new
                        {
                            OwnerId = 4,
                            Name = "Rina"
                        },
                        new
                        {
                            OwnerId = 5,
                            Name = "Adnin"
                        },
                        new
                        {
                            OwnerId = 6,
                            Name = "Mahin"
                        },
                        new
                        {
                            OwnerId = 7,
                            Name = "Aurin"
                        });
                });

            modelBuilder.Entity("EFCore3AndCSharp8.Models.Cat", b =>
                {
                    b.HasOne("EFCore3AndCSharp8.Models.Owner", "Owner")
                        .WithMany("Cats")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
